### PR TITLE
Update setup and README

### PR DESCRIPTION
**Pull request by djKooks**
- Update example in README file
- Update gitignore, for IntelliJ support
Please look on. Thanks.

### CODE REVIEW

**Comment by jeffpeiyt** [comment]
The change lgtm. Thanks so much for the help! 
  However there is some jdk ci error prevented the merge. I am out this weekend and will take a look when I am back

**Comment by jeffpeiyt** [comment]
@djKooks  so sorry still did not get a chance to fix it. Will try this weekend.

**Comment by djKooks** [comment]
@jeffpeiyt No problem. You can just go on any time.

**Comment by jeffpeiyt** [comment]
@djKooks  the issue at my side was fixed. Thanks so much!!

**Pull request merged**
